### ISSUE TITLE
Power off is not working 

### ISSUE THREAD

**Issue by Rjasuja** [intel-aero/packages#10]
After pressing power button for a long time(20 seconds), system didn't switch off.

**Comment by Rjasuja** [comment]
It works after updating the following: 
1. Modifying environment file: /etc/systemd/logind.conf to uncomment `#HandlePowerKey=poweroff`
2. Altering gsettings using `gsettings set com.canonical.indicator.session suppress-logout-restart-shutdown true`

Need to look on how to automate and update as part of a package

**Comment by avinash-palleti** [comment]
> 2.Altering gsettings using  gsettings set com.canonical.indicator.session suppress-logout-restart-shutdown true 

This is required as first line activate power button, up on long press UI will come up to choose among `standby` `reboot` `shutdown` which will not be accessible without HDMI connected.

**Comment by anselmolsm** [comment]
Also, aero-led-ctl uses usleep and it is not available by default. An alternative is to replace usleep 50000 with sleep ~0.5~ 0.05.

**Comment by anselmolsm** [comment]
Please double check
