### ISSUE TITLE
build-pkg.sh: patches dir

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/packages#23]
build-pjg.sh introduced by commit https://github.com/intel-aero/packages/commit/e79247a35fa21ee1d83aef7930ccafa8377891cf looks for content in a PKG_NAME_DIR/patches directory, however patches can be unified under the PKG_NAME_DIR/debian/patches dir instead.

**Comment by avinash-palleti** [comment]
My understanding is it was missed while restructuring to keep patches in respective debian directory, below are the packages which has patches to be applied
```
./aero-utils/debian/patches
./aero-utils/patches
./aero-init/debian/patches
./aero-mavlink-router/debian/patches
./aero-systemd/patches
```
patches which are in `debian` directory does not require build-pkg.sh support to get applied. `debuild` utility will take care while creating packages. 
Other patches also need to be moved to respective debian directories. Please let me know if my understanding is incorrect
I will submit a PR with changes.
