### ISSUE TITLE
Packet loss in mavlink-router

### ISSUE THREAD

**Issue by avinash-palleti** [intel-aero/packages#7]
25% of packet loss is observed in mavlink-router. Before https://github.com/intel-aero/packages/pull/5 this fix 60-70% was observed. After this fix, it is reduced but occasionally observed 25% loss which is still huge.

**Comment by anselmolsm** [comment]
Please see https://github.com/intel-aero/packages/pull/5#issuecomment-343515974

**Comment by avinash-palleti** [comment]
Not seen in this release testing. When we start mavlink-router percentage will be high as number of packets received are less. After sometime loss percentage comes to ~5%
